services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: adm
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: adm
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://adm:adm@db:5432/adm?sslmode=disable
      PORT: 3000
      CORS_ORIGIN: http://localhost:8080
      PAN_BAGNAT_API_BASE_URL: http://localhost
    depends_on:
      - db
    expose:
      - "3000"

  proxy:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  db-data:
